-- changelogs.lua
-- Simple, append-only-ish change log for this workspace (requested by user).
-- Format: a list of entries; each entry includes time, summary, and changed paths.

return {
  {
    at = "Sat 02/07/2026 04:15",
    actor = "codex",
    summary = "Initial scaffold: folders + agent notes + logo copied into assets.",
    changes = {
      { action = "add", path = "AGENTS.md" },
      { action = "add", path = "android/" },
      { action = "add", path = "assets/" },
      { action = "add", path = "assets/css/" },
      { action = "add", path = "assets/js/" },
      { action = "add", path = "assets/img/" },
      { action = "add", path = "assets/img/logo.png" },
      { action = "add", path = "bin/" },
      { action = "add", path = "database/" },
      { action = "add", path = "src/" },
      { action = "add", path = "src/Controllers/" },
      { action = "add", path = "src/Http/" },
      { action = "add", path = "src/Middleware/" },
      { action = "add", path = "src/Models/" },
      { action = "add", path = "src/Views/" },
      { action = "add", path = "src/Views/layouts/" },
      { action = "add", path = "src/Views/public/" },
      { action = "add", path = "src/Views/auth/" },
      { action = "add", path = "src/Views/app/" },
      { action = "add", path = "src/Views/app/partials/" },
      { action = "add", path = "storage/" },
      { action = "add", path = "storage/uploads/" },
      { action = "add", path = "storage/logs/" },
      { action = "add", path = "storage/ratelimit/" },
    },
  },
  {
    at = "Sat 02/07/2026 04:43",
    actor = "codex",
    summary = "Web MVP (PHP+SQLite): routing, sessions, CSRF, rate-limits, migrations/seed, public pages + portal dashboard/leads, and minimal Android-ready API endpoints.",
    changes = {
      { action = "add", path = ".env.example" },
      { action = "add", path = ".htaccess" },
      { action = "add", path = "index.php" },

      { action = "add", path = "assets/css/app.css" },
      { action = "add", path = "assets/js/app.js" },

      { action = "add", path = "src/autoload.php" },
      { action = "add", path = "src/helpers.php" },
      { action = "add", path = "src/Context.php" },
      { action = "add", path = "src/routes.php" },

      { action = "add", path = "src/Support/Env.php" },
      { action = "add", path = "src/Support/Config.php" },
      { action = "add", path = "src/Support/Uuid.php" },
      { action = "add", path = "src/Support/Crypto.php" },
      { action = "add", path = "src/Support/Log.php" },
      { action = "add", path = "src/Support/Upload.php" },

      { action = "add", path = "src/Database/Db.php" },

      { action = "add", path = "src/Http/Request.php" },
      { action = "add", path = "src/Http/Response.php" },
      { action = "add", path = "src/Http/Router.php" },
      { action = "add", path = "src/Http/Session.php" },
      { action = "add", path = "src/Http/Csrf.php" },
      { action = "add", path = "src/Http/Auth.php" },
      { action = "add", path = "src/Http/View.php" },
      { action = "add", path = "src/Http/Middleware.php" },

      { action = "add", path = "src/Middleware/AuthMiddleware.php" },
      { action = "update", path = "src/Middleware/RoleMiddleware.php" },
      { action = "add", path = "src/Middleware/CsrfMiddleware.php" },
      { action = "add", path = "src/Middleware/RateLimitMiddleware.php" },

      { action = "add", path = "src/Controllers/Controller.php" },
      { action = "add", path = "src/Controllers/PublicController.php" },
      { action = "add", path = "src/Controllers/AuthController.php" },
      { action = "add", path = "src/Controllers/App/DashboardController.php" },
      { action = "add", path = "src/Controllers/App/LeadsController.php" },
      { action = "add", path = "src/Controllers/Api/AuthApiController.php" },
      { action = "add", path = "src/Controllers/Api/QuoteRequestsApiController.php" },

      { action = "add", path = "src/Views/layouts/public.php" },
      { action = "add", path = "src/Views/layouts/auth.php" },
      { action = "add", path = "src/Views/layouts/app.php" },

      { action = "add", path = "src/Views/public/home.php" },
      { action = "add", path = "src/Views/public/about.php" },
      { action = "add", path = "src/Views/public/services.php" },
      { action = "add", path = "src/Views/public/gallery.php" },
      { action = "add", path = "src/Views/public/contact.php" },
      { action = "add", path = "src/Views/public/quote_request.php" },
      { action = "add", path = "src/Views/public/quote_request_success.php" },

      { action = "add", path = "src/Views/auth/login.php" },
      { action = "add", path = "src/Views/auth/register.php" },
      { action = "add", path = "src/Views/auth/forgot_password.php" },
      { action = "add", path = "src/Views/auth/reset_password.php" },

      { action = "add", path = "src/Views/app/dashboard.php" },
      { action = "add", path = "src/Views/app/leads_list.php" },
      { action = "add", path = "src/Views/app/lead_detail.php" },

      { action = "add", path = "database/migrations/001_init.sql" },
      { action = "add", path = "bin/migrate.php" },
      { action = "add", path = "bin/seed.php" },
      { action = "add", path = "storage/.htaccess" },
      { action = "add", path = "database/.htaccess" },

      { action = "gen", path = "storage/app.db" },
      { action = "gen", path = "storage/app.db-wal" },
      { action = "gen", path = "storage/app.db-shm" },
    },
  },
  {
    at = "Sat 02/07/2026 04:56",
    actor = "codex",
    summary = "Android app scaffold (Compose) + working Gradle wrapper; created safe junction path to avoid '&' cmd parsing issues.",
    changes = {
      { action = "update", path = "AGENTS.md" },

      { action = "add", path = "c:\\xampp\\htdocs\\ss_ltd (junction -> c:\\xampp\\htdocs\\S&S LTD)" },

      { action = "add", path = "android/README.md" },
      { action = "add", path = "android/settings.gradle.kts" },
      { action = "add", path = "android/build.gradle.kts" },
      { action = "add", path = "android/gradle.properties" },
      { action = "add", path = "android/app/build.gradle.kts" },
      { action = "add", path = "android/app/proguard-rules.pro" },
      { action = "add", path = "android/app/src/main/AndroidManifest.xml" },
      { action = "add", path = "android/app/src/main/res/values/strings.xml" },
      { action = "add", path = "android/app/src/main/java/com/ssltd/fieldapp/MainActivity.kt" },
      { action = "add", path = "android/app/src/main/java/com/ssltd/fieldapp/ui/screens/TodayScreen.kt" },
      { action = "add", path = "android/app/src/main/java/com/ssltd/fieldapp/ui/screens/ProjectsScreen.kt" },
      { action = "add", path = "android/app/src/main/java/com/ssltd/fieldapp/ui/screens/CaptureScreen.kt" },
      { action = "add", path = "android/app/src/main/java/com/ssltd/fieldapp/ui/screens/MessagesScreen.kt" },
      { action = "add", path = "android/app/src/main/java/com/ssltd/fieldapp/ui/screens/ProfileScreen.kt" },
      { action = "add", path = "android/app/src/main/java/com/ssltd/fieldapp/ui/theme/Color.kt" },
      { action = "add", path = "android/app/src/main/java/com/ssltd/fieldapp/ui/theme/Theme.kt" },

      { action = "add", path = "android/gradlew.bat" },
      { action = "add", path = "android/gradlew" },
      { action = "update", path = "android/gradle/wrapper/gradle-wrapper.properties" },
      { action = "add", path = "android/gradle/wrapper/gradle-wrapper.jar" },
      { action = "add", path = "android/gradle/wrapper/gradle-wrapper-shared.jar" },
      { action = "add", path = "android/gradle/wrapper/gradle-cli.jar" },

      { action = "add", path = "storage/tmp/gradle-8.2-bin.zip" },
      { action = "add", path = "storage/tmp/gradle-8.2-contents.txt" },
      { action = "add", path = "storage/tmp/gradle82/" },
      { action = "gen", path = "android/app/build/" },
    },
  },
  {
    at = "Sat 02/07/2026 05:17",
    actor = "codex",
    summary = "Added XAMPP MySQL schema export to bootstrap the DB via phpMyAdmin/import.",
    changes = {
      { action = "add", path = "mysql.sql" },
    },
  },
  {
    at = "Sat 02/07/2026 05:36",
    actor = "codex",
    summary = "Switched default DB to XAMPP MySQL; added MySQL migration file + MySQL-aware migrator; made routing/link generation work when hosted under a subdirectory (e.g. /ss_ltd) by introducing basePath + app_url.",
    changes = {
      { action = "update", path = ".env.example" },
      { action = "update", path = "AGENTS.md" },
      { action = "update", path = "index.php" },
      { action = "update", path = "bin/migrate.php" },
      { action = "update", path = "bin/seed.php" },

      { action = "add", path = "database/migrations/mysql/001_init.sql" },

      { action = "update", path = "src/Context.php" },
      { action = "update", path = "src/helpers.php" },
      { action = "update", path = "src/Database/Db.php" },
      { action = "update", path = "src/Http/Request.php" },
      { action = "update", path = "src/Controllers/Controller.php" },
      { action = "update", path = "src/Middleware/AuthMiddleware.php" },
      { action = "update", path = "src/Middleware/RoleMiddleware.php" },

      { action = "update", path = "src/Views/layouts/public.php" },
      { action = "update", path = "src/Views/layouts/auth.php" },
      { action = "update", path = "src/Views/layouts/app.php" },

      { action = "update", path = "src/Views/public/home.php" },
      { action = "update", path = "src/Views/public/quote_request.php" },
      { action = "update", path = "src/Views/public/quote_request_success.php" },

      { action = "update", path = "src/Views/auth/login.php" },
      { action = "update", path = "src/Views/auth/register.php" },
      { action = "update", path = "src/Views/auth/forgot_password.php" },
      { action = "update", path = "src/Views/auth/reset_password.php" },

      { action = "update", path = "src/Views/app/dashboard.php" },
      { action = "update", path = "src/Views/app/leads_list.php" },
      { action = "update", path = "src/Views/app/lead_detail.php" },
    },
  },
  {
    at = "Sat 02/07/2026 05:37",
    actor = "codex",
    summary = "Hardened web exposure: deny direct access to mysql.sql and .env.example via .htaccess and index.php safeguard.",
    changes = {
      { action = "update", path = ".htaccess" },
      { action = "update", path = "index.php" },
    },
  },
  {
    at = "Sat 02/07/2026 05:38",
    actor = "codex",
    summary = "Docs: clarified Apache URL for the junction path and noted base-path aware routing support.",
    changes = {
      { action = "update", path = "AGENTS.md" },
    },
  },
  {
    at = "Sat 02/07/2026 05:58",
    actor = "codex",
    summary = "Request a Quote: added Simple vs Advanced mode chooser with mode-specific validation; improved responsive layouts by using grid utility classes instead of inline grid-template-columns overrides.",
    changes = {
      { action = "update", path = "src/Controllers/PublicController.php" },
      { action = "update", path = "src/Views/public/quote_request.php" },
      { action = "update", path = "assets/css/app.css" },
      { action = "update", path = "src/Views/app/lead_detail.php" },
    },
  },
  {
    at = "Sat 02/07/2026 06:09",
    actor = "codex",
    summary = "Added release-oriented checklist and step-by-step plan for WEB + Android (v0.1 MVP scope + gates).",
    changes = {
      { action = "add", path = "full_todos.md" },
    },
  },
  {
    at = "Sat 02/07/2026 06:25",
    actor = "codex",
    summary = "Portal: implemented Projects list/detail, Messages inbox/thread/send (threads auto-created for leads/projects), and secure streaming downloads for uploads; updated full_todos progress.",
    changes = {
      { action = "update", path = "src/Http/Response.php" },
      { action = "add", path = "src/Controllers/App/UploadsController.php" },
      { action = "add", path = "src/Controllers/App/ProjectsController.php" },
      { action = "add", path = "src/Controllers/App/MessagesController.php" },
      { action = "update", path = "src/Controllers/App/LeadsController.php" },
      { action = "update", path = "src/routes.php" },
      { action = "update", path = "src/Views/layouts/app.php" },
      { action = "add", path = "src/Views/app/projects_list.php" },
      { action = "add", path = "src/Views/app/project_detail.php" },
      { action = "add", path = "src/Views/app/messages_inbox.php" },
      { action = "add", path = "src/Views/app/messages_thread.php" },
      { action = "update", path = "src/Views/app/lead_detail.php" },
      { action = "update", path = "full_todos.md" },
    },
  },
  {
    at = "Sat 02/07/2026 06:40",
    actor = "codex",
    summary = "Backend/API: added project membership table + indexes, expanded seed with an employee + sample project membership, implemented Android MVP API endpoints (projects, threads/messages, timesheets, uploads), and made bearer parsing more tolerant; updated full_todos progress.",
    changes = {
      { action = "add", path = "database/migrations/002_project_members.sql" },
      { action = "add", path = "database/migrations/mysql/002_project_members.sql" },
      { action = "update", path = "mysql.sql" },
      { action = "update", path = "bin/seed.php" },

      { action = "update", path = "src/Http/Request.php" },
      { action = "update", path = "src/Controllers/Api/AuthApiController.php" },
      { action = "add", path = "src/Controllers/Api/ProjectsApiController.php" },
      { action = "add", path = "src/Controllers/Api/ThreadsApiController.php" },
      { action = "add", path = "src/Controllers/Api/TimesheetsApiController.php" },
      { action = "add", path = "src/Controllers/Api/UploadsApiController.php" },
      { action = "update", path = "src/routes.php" },

      { action = "update", path = "full_todos.md" },

      { action = "del", path = "storage/tmp/login_employee.json" },
      { action = "del", path = "storage/tmp/q.txt" },
      { action = "del", path = "storage/tmp/q2.txt" },
    },
  },
  {
    at = "Sat 02/07/2026 06:48",
    actor = "codex",
    summary = "Android app: added Retrofit/OkHttp client, encrypted auth storage, login screen, and wired Projects screen to the backend API (debug base URL via BuildConfig). Updated full_todos progress.",
    changes = {
      { action = "update", path = "android/app/build.gradle.kts" },
      { action = "update", path = "android/app/src/main/AndroidManifest.xml" },
      { action = "add", path = "android/app/src/main/java/com/ssltd/fieldapp/data/AuthStore.kt" },
      { action = "add", path = "android/app/src/main/java/com/ssltd/fieldapp/data/api/ApiClient.kt" },
      { action = "add", path = "android/app/src/main/java/com/ssltd/fieldapp/data/api/ApiModels.kt" },
      { action = "add", path = "android/app/src/main/java/com/ssltd/fieldapp/data/api/SsApi.kt" },
      { action = "add", path = "android/app/src/main/java/com/ssltd/fieldapp/ui/screens/LoginScreen.kt" },
      { action = "update", path = "android/app/src/main/java/com/ssltd/fieldapp/MainActivity.kt" },
      { action = "update", path = "android/app/src/main/java/com/ssltd/fieldapp/ui/screens/ProjectsScreen.kt" },
      { action = "update", path = "android/app/src/main/java/com/ssltd/fieldapp/ui/screens/ProfileScreen.kt" },
      { action = "update", path = "full_todos.md" },
    },
  },
  {
    at = "Sat 02/07/2026 06:52",
    actor = "codex",
    summary = "Android app: wired Today (timesheet start/stop) and Messages (project thread + send) screens to the backend API; updated full_todos progress.",
    changes = {
      { action = "update", path = "android/app/src/main/java/com/ssltd/fieldapp/MainActivity.kt" },
      { action = "update", path = "android/app/src/main/java/com/ssltd/fieldapp/ui/screens/TodayScreen.kt" },
      { action = "add", path = "android/app/src/main/java/com/ssltd/fieldapp/ui/screens/MessagesScreen.kt" },
      { action = "update", path = "full_todos.md" },
    },
  },
  {
    at = "Sat 02/07/2026 06:55",
    actor = "codex",
    summary = "Web portal: added Admin Users management (list/create/set password) and Audit Log pages; exposed Admin links in sidebar for admins; updated full_todos progress.",
    changes = {
      { action = "add", path = "src/Controllers/App/Admin/UsersController.php" },
      { action = "add", path = "src/Controllers/App/Admin/AuditController.php" },
      { action = "add", path = "src/Views/app/admin_users.php" },
      { action = "add", path = "src/Views/app/admin_audit.php" },
      { action = "update", path = "src/routes.php" },
      { action = "update", path = "src/Views/layouts/app.php" },
      { action = "update", path = "full_todos.md" },
    },
  },
  {
    at = "Sat 02/07/2026 06:57",
    actor = "codex",
    summary = "Web portal: completed Admin user role/status updates and added audit log filtering by action/entity type; updated full_todos progress.",
    changes = {
      { action = "update", path = "src/Controllers/App/Admin/UsersController.php" },
      { action = "update", path = "src/Views/app/admin_users.php" },
      { action = "update", path = "src/Controllers/App/Admin/AuditController.php" },
      { action = "update", path = "src/Views/app/admin_audit.php" },
      { action = "update", path = "src/routes.php" },
      { action = "update", path = "full_todos.md" },
    },
  },
  {
    at = "Sat 02/07/2026 07:02",
    actor = "codex",
    summary = "Client portal: added client-scoped leads/projects pages, client-aware dashboard KPIs, and enabled Messages for clients with ACL checks. Updated app sidebar links and full_todos progress.",
    changes = {
      { action = "update", path = "src/Views/layouts/app.php" },
      { action = "update", path = "src/Controllers/App/DashboardController.php" },
      { action = "add", path = "src/Controllers/App/Client/LeadsController.php" },
      { action = "add", path = "src/Controllers/App/Client/ProjectsController.php" },
      { action = "add", path = "src/Views/app/client_leads_list.php" },
      { action = "add", path = "src/Views/app/client_lead_detail.php" },
      { action = "add", path = "src/Views/app/client_projects_list.php" },
      { action = "add", path = "src/Views/app/client_project_detail.php" },
      { action = "update", path = "src/Controllers/App/MessagesController.php" },
      { action = "update", path = "src/Views/app/messages_inbox.php" },
      { action = "update", path = "src/Views/app/messages_thread.php" },
      { action = "update", path = "src/routes.php" },
      { action = "update", path = "full_todos.md" },
    },
  },
  {
    at = "Sat 02/07/2026 07:03",
    actor = "codex",
    summary = "Client portal hardening: client lead attachments list now shows only client-visible files or files uploaded by that client.",
    changes = {
      { action = "update", path = "src/Controllers/App/Client/LeadsController.php" },
    },
  },
  {
    at = "Sat 02/07/2026 08:30",
    actor = "codex",
    summary = "Android: implemented Capture (camera + file picker) with Room-backed offline upload queue and WorkManager background uploads; added global offline indicator and auto-logout on API 401.",
    changes = {
      { action = "update", path = "android/app/build.gradle.kts" },
      { action = "update", path = "android/app/src/main/AndroidManifest.xml" },
      { action = "add", path = "android/app/src/main/res/xml/file_paths.xml" },

      { action = "update", path = "android/app/src/main/java/com/ssltd/fieldapp/MainActivity.kt" },
      { action = "update", path = "android/app/src/main/java/com/ssltd/fieldapp/data/AuthStore.kt" },
      { action = "add", path = "android/app/src/main/java/com/ssltd/fieldapp/data/NetworkMonitor.kt" },
      { action = "add", path = "android/app/src/main/java/com/ssltd/fieldapp/data/PendingFiles.kt" },
      { action = "update", path = "android/app/src/main/java/com/ssltd/fieldapp/data/api/ApiClient.kt" },
      { action = "update", path = "android/app/src/main/java/com/ssltd/fieldapp/data/api/SsApi.kt" },
      { action = "add", path = "android/app/src/main/java/com/ssltd/fieldapp/data/db/AppDb.kt" },
      { action = "add", path = "android/app/src/main/java/com/ssltd/fieldapp/data/db/QueuedUpload.kt" },
      { action = "add", path = "android/app/src/main/java/com/ssltd/fieldapp/data/db/QueuedUploadDao.kt" },
      { action = "add", path = "android/app/src/main/java/com/ssltd/fieldapp/work/UploadWork.kt" },
      { action = "add", path = "android/app/src/main/java/com/ssltd/fieldapp/work/UploadWorker.kt" },
      { action = "update", path = "android/app/src/main/java/com/ssltd/fieldapp/ui/screens/CaptureScreen.kt" },
    },
  },
  {
    at = "Sat 02/07/2026 08:36",
    actor = "codex",
    summary = "Web/API: added pagination for Leads/Projects/Messages (web) and Projects list (API); implemented lead/project status transitions with audit logging; added client Approvals placeholder page and nav link.",
    changes = {
      { action = "update", path = "src/routes.php" },

      { action = "update", path = "src/Controllers/Controller.php" },
      { action = "update", path = "src/Controllers/App/LeadsController.php" },
      { action = "update", path = "src/Controllers/App/ProjectsController.php" },
      { action = "update", path = "src/Controllers/App/MessagesController.php" },
      { action = "add", path = "src/Controllers/App/Client/ApprovalsController.php" },

      { action = "update", path = "src/Controllers/Api/ProjectsApiController.php" },

      { action = "add", path = "src/Views/app/partials/pagination.php" },
      { action = "update", path = "src/Views/app/leads_list.php" },
      { action = "update", path = "src/Views/app/projects_list.php" },
      { action = "update", path = "src/Views/app/messages_inbox.php" },
      { action = "update", path = "src/Views/app/lead_detail.php" },
      { action = "update", path = "src/Views/app/project_detail.php" },
      { action = "add", path = "src/Views/app/client_approvals.php" },
      { action = "update", path = "src/Views/layouts/app.php" },

      { action = "update", path = "full_todos.md" },
    },
  },
  {
    at = "Sat 02/07/2026 08:37",
    actor = "codex",
    summary = "API: added pagination (page/per_page + meta.has_more) to quote requests list endpoint.",
    changes = {
      { action = "update", path = "src/Controllers/Api/QuoteRequestsApiController.php" },
    },
  },
  {
    at = "Sat 02/07/2026 08:45",
    actor = "codex",
    summary = "Android: added Projects detail screen and navigation (projects -> project/{id}) backed by GET /api/projects/{id}; updated models to include client fields; marked Projects detail as done in full_todos.",
    changes = {
      { action = "update", path = "android/app/src/main/java/com/ssltd/fieldapp/data/api/SsApi.kt" },
      { action = "update", path = "android/app/src/main/java/com/ssltd/fieldapp/data/api/ApiModels.kt" },
      { action = "update", path = "android/app/src/main/java/com/ssltd/fieldapp/ui/screens/ProjectsScreen.kt" },
      { action = "add", path = "android/app/src/main/java/com/ssltd/fieldapp/ui/screens/ProjectDetailScreen.kt" },
      { action = "update", path = "android/app/src/main/java/com/ssltd/fieldapp/MainActivity.kt" },
      { action = "update", path = "full_todos.md" },
    },
  },
  {
    at = "Sat 02/07/2026 08:52",
    actor = "codex",
    summary = "Android: added elapsed timer UI for running timesheet on Today screen; marked item as done in full_todos.",
    changes = {
      { action = "update", path = "android/app/src/main/java/com/ssltd/fieldapp/ui/screens/TodayScreen.kt" },
      { action = "update", path = "full_todos.md" },
    },
  },
  {
    at = "Sat 02/07/2026 08:57",
    actor = "codex",
    summary = "Android: implemented message attachments (photo/file) by enqueueing uploads to the existing offline queue (Room + WorkManager) as project docs; marked item as done in full_todos.",
    changes = {
      { action = "update", path = "android/app/src/main/java/com/ssltd/fieldapp/ui/screens/MessagesScreen.kt" },
      { action = "update", path = "full_todos.md" },
    },
  },
  {
    at = "Sat 02/07/2026 09:03",
    actor = "codex",
    summary = "Web portal: added staff upload forms for leads/projects, client-visible toggle for uploads, enabled client downloads with ACL, and added client project files list; marked uploads visibility TODO as done.",
    changes = {
      { action = "update", path = "src/routes.php" },
      { action = "update", path = "src/Controllers/App/UploadsController.php" },
      { action = "update", path = "src/Controllers/App/LeadsController.php" },
      { action = "update", path = "src/Controllers/App/ProjectsController.php" },
      { action = "update", path = "src/Controllers/App/Client/ProjectsController.php" },
      { action = "update", path = "src/Views/app/lead_detail.php" },
      { action = "update", path = "src/Views/app/project_detail.php" },
      { action = "update", path = "src/Views/app/client_lead_detail.php" },
      { action = "update", path = "src/Views/app/client_project_detail.php" },
      { action = "update", path = "full_todos.md" },
    },
  },
  {
    at = "Sat 02/07/2026 09:05",
    actor = "codex",
    summary = "Android privacy hardening: strip GPS EXIF tags from camera-captured JPEGs before queueing uploads (Capture + Messages); marked item as done in full_todos.",
    changes = {
      { action = "update", path = "android/app/build.gradle.kts" },
      { action = "add", path = "android/app/src/main/java/com/ssltd/fieldapp/data/ExifSanitizer.kt" },
      { action = "update", path = "android/app/src/main/java/com/ssltd/fieldapp/ui/screens/CaptureScreen.kt" },
      { action = "update", path = "android/app/src/main/java/com/ssltd/fieldapp/ui/screens/MessagesScreen.kt" },
      { action = "update", path = "full_todos.md" },
    },
  },
  {
    at = "Sat 02/07/2026 09:06",
    actor = "codex",
    summary = "DB/perf: added index migrations for common list ordering; updated mysql.sql schema export; marked DB indexes TODO as done.",
    changes = {
      { action = "add", path = "database/migrations/003_indexes.sql" },
      { action = "add", path = "database/migrations/mysql/003_indexes.sql" },
      { action = "update", path = "mysql.sql" },
      { action = "update", path = "full_todos.md" },
      { action = "gen", path = "migrations (applied 003_indexes.sql)" },
    },
  },
  {
    at = "Sat 02/07/2026 09:08",
    actor = "codex",
    summary = "Ops/perf: added Apache caching+compression rules, implemented size-based log rotation, added DB/migrations health scripts, and expanded API rate limiting; updated full_todos.",
    changes = {
      { action = "update", path = ".htaccess" },
      { action = "update", path = "src/Support/Log.php" },
      { action = "add", path = "bin/health_db.php" },
      { action = "add", path = "bin/migrate_status.php" },
      { action = "update", path = "src/routes.php" },
      { action = "update", path = "full_todos.md" },
    },
  },
  {
    at = "Sat 02/07/2026 09:10",
    actor = "codex",
    summary = "API/auth: added refresh endpoint, injected X-Request-Id into responses (and JSON), and marked API auth standardization items as done in full_todos.",
    changes = {
      { action = "add", path = "src/Support/RequestId.php" },
      { action = "update", path = "index.php" },
      { action = "update", path = "src/Http/Response.php" },
      { action = "update", path = "src/Http/Auth.php" },
      { action = "update", path = "src/Controllers/Api/AuthApiController.php" },
      { action = "update", path = "src/routes.php" },
      { action = "update", path = "full_todos.md" },
    },
  },
  {
    at = "Sat 02/07/2026 09:13",
    actor = "codex",
    summary = "Backend hardening: introduced Validate helper and applied it to key controllers; added best-effort server-side image re-encode in uploads; documented background job strategy; updated full_todos.",
    changes = {
      { action = "add", path = "src/Support/Validate.php" },
      { action = "update", path = "src/Controllers/PublicController.php" },
      { action = "update", path = "src/Controllers/Api/AuthApiController.php" },
      { action = "update", path = "src/Controllers/Api/QuoteRequestsApiController.php" },
      { action = "update", path = "src/Controllers/App/Admin/UsersController.php" },
      { action = "update", path = "src/Support/Upload.php" },
      { action = "add", path = "docs/background_jobs.md" },
      { action = "update", path = "full_todos.md" },
    },
  },
  {
    at = "Sat 02/07/2026 09:19",
    actor = "codex",
    summary = "Android release: enabled R8/proguard for release builds with env-driven signing config fallback; added required errorprone annotations dependency; updated full_todos.",
    changes = {
      { action = "update", path = "android/app/build.gradle.kts" },
      { action = "update", path = "android/app/proguard-rules.pro" },
      { action = "update", path = "full_todos.md" },
    },
  },
  {
    at = "Sat 02/07/2026 09:21",
    actor = "codex",
    summary = "DB/model: added subcontractor tables (mysql+sqlite migrations), expanded admin role options + seed accounts, updated mysql.sql export, and marked DB role/migration TODOs as done.",
    changes = {
      { action = "add", path = "database/migrations/004_subcontractors.sql" },
      { action = "add", path = "database/migrations/mysql/004_subcontractors.sql" },
      { action = "update", path = "src/Controllers/App/Admin/UsersController.php" },
      { action = "update", path = "src/Views/app/admin_users.php" },
      { action = "update", path = "bin/seed.php" },
      { action = "update", path = "mysql.sql" },
      { action = "update", path = "full_todos.md" },
      { action = "gen", path = "migrations (applied 004_subcontractors.sql)" },
    },
  },
  {
    at = "Sat 02/07/2026 09:23",
    actor = "codex",
    summary = "Web portal: added Timesheets list page and expanded sidebar with planned sections to match screen list; marked portal navigation TODO as done.",
    changes = {
      { action = "add", path = "src/Controllers/App/TimesheetsController.php" },
      { action = "add", path = "src/Views/app/timesheets_list.php" },
      { action = "update", path = "src/routes.php" },
      { action = "update", path = "src/Views/layouts/app.php" },
      { action = "update", path = "full_todos.md" },
    },
  },
  {
    at = "Sat 02/07/2026 09:24",
    actor = "codex",
    summary = "Web messages: added thread read tracking (thread_reads) and unread badge in inbox; marked read/unread TODO as done; updated mysql.sql export.",
    changes = {
      { action = "add", path = "database/migrations/005_thread_reads.sql" },
      { action = "add", path = "database/migrations/mysql/005_thread_reads.sql" },
      { action = "update", path = "mysql.sql" },
      { action = "update", path = "src/Controllers/App/MessagesController.php" },
      { action = "update", path = "src/Views/app/messages_inbox.php" },
      { action = "update", path = "full_todos.md" },
      { action = "gen", path = "migrations (applied 005_thread_reads.sql)" },
    },
  },
  {
    at = "Sat 02/07/2026 09:44",
    actor = "codex",
    summary = "Release-gate hardening: enabled CSP + prod config enforcement, added /health endpoints + smoke/lint scripts, documented privacy/terms/backups/testing, and improved brute-force protections (rate limit by IP+email). Updated full_todos accordingly.",
    changes = {
      { action = "update", path = "index.php" },
      { action = "update", path = "src/Support/Config.php" },

      { action = "update", path = "src/Http/Request.php" },
      { action = "update", path = "src/Middleware/RateLimitMiddleware.php" },
      { action = "update", path = "src/routes.php" },

      { action = "add", path = "src/Controllers/HealthController.php" },
      { action = "update", path = "src/Controllers/PublicController.php" },
      { action = "add", path = "src/Views/public/privacy.php" },
      { action = "add", path = "src/Views/public/terms.php" },
      { action = "update", path = "src/Views/layouts/public.php" },
      { action = "update", path = "assets/css/app.css" },

      { action = "update", path = ".env.example" },
      { action = "update", path = "full_todos.md" },

      { action = "add", path = "docs/backups.md" },
      { action = "add", path = "docs/manual_test_checklist.md" },
      { action = "add", path = "docs/setup.md" },
      { action = "add", path = "docs/conflict_strategy.md" },

      { action = "add", path = "bin/smoke_http.php" },
      { action = "add", path = "bin/php_lint.php" },
      { action = "add", path = "bin/check_full_todos_done.php" },
    },
  },
  {
    at = "Sat 02/07/2026 09:45",
    actor = "codex",
    summary = "Updated full_todos current-state summary to reflect the implemented WEB/API/Android MVP.",
    changes = {
      { action = "update", path = "full_todos.md" },
    },
  },
  {
    at = "Sat 02/07/2026 09:49",
    actor = "codex",
    summary = "Android phase 2: added Room offline cache for projects + threads/messages and wired Projects/ProjectDetail/Messages screens to use cache when offline or on API failure. Updated full_todos backlog with v0.2 checklist.",
    changes = {
      { action = "update", path = "android/app/src/main/java/com/ssltd/fieldapp/MainActivity.kt" },
      { action = "update", path = "android/app/src/main/java/com/ssltd/fieldapp/data/db/AppDb.kt" },
      { action = "add", path = "android/app/src/main/java/com/ssltd/fieldapp/data/db/CachedProject.kt" },
      { action = "add", path = "android/app/src/main/java/com/ssltd/fieldapp/data/db/CachedProjectDao.kt" },
      { action = "add", path = "android/app/src/main/java/com/ssltd/fieldapp/data/db/CachedThread.kt" },
      { action = "add", path = "android/app/src/main/java/com/ssltd/fieldapp/data/db/CachedThreadDao.kt" },
      { action = "add", path = "android/app/src/main/java/com/ssltd/fieldapp/data/db/CachedMessage.kt" },
      { action = "add", path = "android/app/src/main/java/com/ssltd/fieldapp/data/db/CachedMessageDao.kt" },
      { action = "update", path = "android/app/src/main/java/com/ssltd/fieldapp/ui/screens/ProjectsScreen.kt" },
      { action = "update", path = "android/app/src/main/java/com/ssltd/fieldapp/ui/screens/ProjectDetailScreen.kt" },
      { action = "update", path = "android/app/src/main/java/com/ssltd/fieldapp/ui/screens/MessagesScreen.kt" },
      { action = "update", path = "full_todos.md" },
    },
  },
  {
    at = "Sat 02/07/2026 09:59",
    actor = "codex",
    summary = "CSP follow-up + Android v0.2 completion: removed remaining inline styles from portal views to match strict CSP; added optional Sentry crash reporting for Android; marked v0.2 backlog items as done and added helper script to find unchecked todos.",
    changes = {
      { action = "update", path = "assets/css/app.css" },

      { action = "update", path = "src/Views/app/dashboard.php" },
      { action = "update", path = "src/Views/app/client_approvals.php" },
      { action = "update", path = "src/Views/app/client_leads_list.php" },
      { action = "update", path = "src/Views/app/client_lead_detail.php" },
      { action = "update", path = "src/Views/app/leads_list.php" },
      { action = "update", path = "src/Views/app/lead_detail.php" },
      { action = "update", path = "src/Views/app/messages_inbox.php" },
      { action = "update", path = "src/Views/app/messages_thread.php" },
      { action = "update", path = "src/Views/app/projects_list.php" },
      { action = "update", path = "src/Views/app/project_detail.php" },
      { action = "update", path = "src/Views/app/timesheets_list.php" },
      { action = "update", path = "src/Views/app/partials/pagination.php" },

      { action = "update", path = "android/app/build.gradle.kts" },
      { action = "update", path = "android/app/src/main/AndroidManifest.xml" },
      { action = "add", path = "android/app/src/main/java/com/ssltd/fieldapp/SsApp.kt" },

      { action = "update", path = "full_todos.md" },
      { action = "add", path = "bin/find_unchecked_todos.php" },
    },
  },
  {
    at = "Sat 02/07/2026 10:11",
    actor = "codex",
    summary = "Implemented quote checklist/estimate workflow: DB tables+migrations for checklists/items, staff lead checklist builder + submit, client approvals list/detail + approve/reject, and best-effort checklist copy when converting lead->project. Updated mysql.sql, seed, routes, and full_todos.",
    changes = {
      { action = "add", path = "database/migrations/006_checklists.sql" },
      { action = "add", path = "database/migrations/mysql/006_checklists.sql" },
      { action = "update", path = "mysql.sql" },

      { action = "add", path = "src/Controllers/App/ChecklistsController.php" },
      { action = "update", path = "src/Controllers/App/LeadsController.php" },
      { action = "update", path = "src/Controllers/App/Client/ApprovalsController.php" },
      { action = "update", path = "src/routes.php" },

      { action = "add", path = "src/Views/app/lead_checklist.php" },
      { action = "add", path = "src/Views/app/client_approval_detail.php" },
      { action = "update", path = "src/Views/app/client_approvals.php" },
      { action = "update", path = "src/Views/app/lead_detail.php" },

      { action = "update", path = "assets/css/app.css" },

      { action = "update", path = "bin/seed.php" },
      { action = "update", path = "full_todos.md" },

      { action = "gen", path = "migrations (applied 006_checklists.sql)" },
    },
  },
  {
    at = "Sat 02/07/2026 10:15",
    actor = "codex",
    summary = "Implemented project checklist API + Android UI: added API endpoints to fetch current project checklist and update checklist item status; added Android ProjectChecklist screen and wired navigation from project details; updated full_todos.",
    changes = {
      { action = "add", path = "src/Controllers/Api/ChecklistsApiController.php" },
      { action = "update", path = "src/routes.php" },

      { action = "update", path = "android/app/src/main/java/com/ssltd/fieldapp/data/api/ApiModels.kt" },
      { action = "update", path = "android/app/src/main/java/com/ssltd/fieldapp/data/api/SsApi.kt" },
      { action = "add", path = "android/app/src/main/java/com/ssltd/fieldapp/ui/screens/ProjectChecklistScreen.kt" },
      { action = "update", path = "android/app/src/main/java/com/ssltd/fieldapp/ui/screens/ProjectDetailScreen.kt" },
      { action = "update", path = "android/app/src/main/java/com/ssltd/fieldapp/MainActivity.kt" },

      { action = "update", path = "full_todos.md" },
      { action = "update", path = "assets/css/app.css" },
    },
  },
  {
    at = "Sat 02/07/2026 10:27",
    actor = "codex",
    summary = "WEB: implemented schedule proposals and client approval flow (proposal detail + approve/reject w/ optional note), added schedule DB tables (migrations+mysql.sql), seeded a demo schedule proposal, and updated full_todos.",
    changes = {
      { action = "update", path = "database/migrations/007_schedule.sql" },
      { action = "update", path = "database/migrations/mysql/007_schedule.sql" },
      { action = "update", path = "mysql.sql" },

      { action = "update", path = "src/Controllers/App/Client/ApprovalsController.php" },
      { action = "add", path = "src/Views/app/client_schedule_detail.php" },
      { action = "update", path = "src/Views/app/project_detail.php" },

      { action = "update", path = "assets/css/app.css" },
      { action = "update", path = "bin/seed.php" },
      { action = "update", path = "full_todos.md" },

      { action = "gen", path = "migrations (applied 007_schedule.sql)" },
    },
  },
  {
    at = "Sat 02/07/2026 10:36",
    actor = "codex",
    summary = "WEB: implemented Inventory catalogs (materials/tools) with list/create/edit screens; added inventory DB tables + migrations (MySQL+SQLite) and updated mysql.sql; enabled Inventory nav link; expanded seed with sample materials/tools; updated full_todos.",
    changes = {
      { action = "add", path = "database/migrations/008_inventory.sql" },
      { action = "add", path = "database/migrations/mysql/008_inventory.sql" },
      { action = "update", path = "mysql.sql" },

      { action = "add", path = "src/Controllers/App/InventoryController.php" },
      { action = "update", path = "src/routes.php" },
      { action = "update", path = "src/Views/layouts/app.php" },

      { action = "add", path = "src/Views/app/inventory_materials.php" },
      { action = "add", path = "src/Views/app/inventory_material_detail.php" },
      { action = "add", path = "src/Views/app/inventory_tools.php" },
      { action = "add", path = "src/Views/app/inventory_tool_detail.php" },

      { action = "update", path = "bin/seed.php" },
      { action = "update", path = "full_todos.md" },

      { action = "gen", path = "migrations (applied 008_inventory.sql)" },
    },
  },
  {
    at = "Sat 02/07/2026 10:37",
    actor = "codex",
    summary = "WEB: updated project detail copy to reflect implemented tabs (Schedule/Files already present).",
    changes = {
      { action = "update", path = "src/Views/app/project_detail.php" },
    },
  },
  {
    at = "Sat 02/07/2026 10:43",
    actor = "codex",
    summary = "WEB: wired project-level inventory usage (materials/tools allocations + deliveries CRUD) into Project detail; added ProjectInventoryController, routes, and seed demo data; updated full_todos.",
    changes = {
      { action = "add", path = "src/Controllers/App/ProjectInventoryController.php" },
      { action = "update", path = "src/routes.php" },
      { action = "update", path = "src/Controllers/App/ProjectsController.php" },
      { action = "update", path = "src/Views/app/project_detail.php" },
      { action = "update", path = "bin/seed.php" },
      { action = "update", path = "full_todos.md" },
    },
  },
  {
    at = "Sat 02/07/2026 10:47",
    actor = "codex",
    summary = "API+Android: added schedule feed endpoint (/api/schedule) with role-based ACL filtering; Android Today now shows upcoming schedule events with Room cache fallback; updated full_todos.",
    changes = {
      { action = "add", path = "src/Controllers/Api/ScheduleApiController.php" },
      { action = "update", path = "src/routes.php" },

      { action = "update", path = "android/app/src/main/java/com/ssltd/fieldapp/data/api/ApiModels.kt" },
      { action = "update", path = "android/app/src/main/java/com/ssltd/fieldapp/data/api/SsApi.kt" },
      { action = "update", path = "android/app/src/main/java/com/ssltd/fieldapp/ui/screens/TodayScreen.kt" },

      { action = "add", path = "android/app/src/main/java/com/ssltd/fieldapp/data/db/CachedScheduleEvent.kt" },
      { action = "add", path = "android/app/src/main/java/com/ssltd/fieldapp/data/db/CachedScheduleEventDao.kt" },
      { action = "update", path = "android/app/src/main/java/com/ssltd/fieldapp/data/db/AppDb.kt" },

      { action = "update", path = "full_todos.md" },
    },
  },
  {
    at = "Sat 02/07/2026 10:55",
    actor = "codex",
    summary = "WEB+API+Android: added project Reports and Issues (DB tables+migrations+mysql.sql, portal UI on Project detail, API endpoints, and Android quick actions/screens).",
    changes = {
      { action = "add", path = "database/migrations/009_reports_issues.sql" },
      { action = "add", path = "database/migrations/mysql/009_reports_issues.sql" },
      { action = "update", path = "mysql.sql" },

      { action = "add", path = "src/Controllers/App/ProjectReportsController.php" },
      { action = "add", path = "src/Controllers/App/ProjectIssuesController.php" },
      { action = "update", path = "src/routes.php" },
      { action = "update", path = "src/Controllers/App/ProjectsController.php" },
      { action = "update", path = "src/Views/app/project_detail.php" },
      { action = "update", path = "bin/seed.php" },

      { action = "add", path = "src/Controllers/Api/ReportsApiController.php" },
      { action = "add", path = "src/Controllers/Api/IssuesApiController.php" },
      { action = "update", path = "src/routes.php" },

      { action = "update", path = "android/app/src/main/java/com/ssltd/fieldapp/data/api/ApiModels.kt" },
      { action = "update", path = "android/app/src/main/java/com/ssltd/fieldapp/data/api/SsApi.kt" },
      { action = "add", path = "android/app/src/main/java/com/ssltd/fieldapp/ui/screens/AddReportScreen.kt" },
      { action = "add", path = "android/app/src/main/java/com/ssltd/fieldapp/ui/screens/IssuesScreen.kt" },
      { action = "update", path = "android/app/src/main/java/com/ssltd/fieldapp/ui/screens/ProjectDetailScreen.kt" },
      { action = "update", path = "android/app/src/main/java/com/ssltd/fieldapp/MainActivity.kt" },

      { action = "update", path = "full_todos.md" },
      { action = "gen", path = "migrations (applied 009_reports_issues.sql)" },
    },
  },
  {
    at = "Sat 02/07/2026 10:57",
    actor = "codex",
    summary = "Android: cleaned up Issues screen rendering to avoid a Kotlin warning.",
    changes = {
      { action = "update", path = "android/app/src/main/java/com/ssltd/fieldapp/ui/screens/IssuesScreen.kt" },
    },
  },
  {
    at = "Sat 02/07/2026 11:03",
    actor = "codex",
    summary = "WEB: implemented Change Requests workflow with client approvals (DB+migrations+mysql.sql, staff create/submit from Project detail, client approvals list/detail + approve/reject), and seeded a demo pending change request.",
    changes = {
      { action = "add", path = "database/migrations/010_change_requests.sql" },
      { action = "add", path = "database/migrations/mysql/010_change_requests.sql" },
      { action = "update", path = "mysql.sql" },

      { action = "add", path = "src/Controllers/App/ProjectChangeRequestsController.php" },
      { action = "update", path = "src/routes.php" },
      { action = "update", path = "src/Controllers/App/ProjectsController.php" },
      { action = "update", path = "src/Controllers/App/Client/ApprovalsController.php" },

      { action = "update", path = "src/Views/app/project_detail.php" },
      { action = "update", path = "src/Views/app/client_approvals.php" },
      { action = "add", path = "src/Views/app/client_change_request_detail.php" },

      { action = "update", path = "assets/css/app.css" },
      { action = "update", path = "bin/seed.php" },
      { action = "update", path = "full_todos.md" },

      { action = "gen", path = "migrations (applied 010_change_requests.sql)" },
    },
  },
  {
    at = "Sat 02/07/2026 11:06",
    actor = "codex",
    summary = "WEB: implemented People module (subcontractors list/detail + worker approval) and enabled People nav link; added pending worker seed for approval demo.",
    changes = {
      { action = "add", path = "src/Controllers/App/People/SubcontractorsController.php" },
      { action = "update", path = "src/routes.php" },
      { action = "update", path = "src/Views/layouts/app.php" },
      { action = "add", path = "src/Views/app/people_subcontractors.php" },
      { action = "add", path = "src/Views/app/people_subcontractor_detail.php" },
      { action = "update", path = "bin/seed.php" },
      { action = "update", path = "full_todos.md" },
    },
  },
  {
    at = "Sat 02/07/2026 11:12",
    actor = "codex",
    summary = "WEB: expanded Schedule into a week/month calendar with event CRUD (create/update/cancel) and best-effort conflict detection per assigned PM; added seed schedule event; updated full_todos.",
    changes = {
      { action = "update", path = "src/Controllers/App/ScheduleController.php" },
      { action = "update", path = "src/routes.php" },
      { action = "update", path = "src/Views/app/schedule.php" },
      { action = "update", path = "bin/seed.php" },
      { action = "update", path = "full_todos.md" },
    },
  },
  {
    at = "Sat 02/07/2026 11:27",
    actor = "codex",
    summary = "WEB: added Project checklist page (routing + view) with draft vs locked behavior; linked from Project detail; seeded demo project checklist items; updated full_todos.",
    changes = {
      { action = "update", path = "src/routes.php" },
      { action = "update", path = "src/Controllers/App/ProjectChecklistController.php" },
      { action = "add", path = "src/Views/app/project_checklist.php" },
      { action = "update", path = "src/Views/app/project_detail.php" },
      { action = "update", path = "bin/seed.php" },
      { action = "update", path = "full_todos.md" },
    },
  },
  {
    at = "Sat 02/07/2026 11:51",
    actor = "codex",
    summary = "Android: fixed release lint error (camera permission implies feature), added launcher icon resources, and made API base URL configurable via env vars for debug/release builds; verified lintRelease + assembleRelease + bundleRelease.",
    changes = {
      { action = "update", path = "android/app/src/main/AndroidManifest.xml" },
      { action = "update", path = "android/app/build.gradle.kts" },
      { action = "add", path = "android/app/src/main/res/values/ic_launcher_background.xml" },
      { action = "add", path = "android/app/src/main/res/drawable/ic_launcher_foreground.xml" },
      { action = "add", path = "android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml" },
      { action = "add", path = "android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml" },
    },
  },
  {
    at = "Sat 02/07/2026 12:02",
    actor = "codex",
    summary = "Android: renamed app label to S&S (app_name).",
    changes = {
      { action = "update", path = "android/app/src/main/res/values/strings.xml" },
    },
  },
  {
    at = "Sat 02/07/2026 12:21",
    actor = "codex",
    summary = "Android: fixed startup crash when Sentry DSN is empty by disabling Sentry ContentProvider auto-init (manual init remains in SsApp).",
    changes = {
      { action = "update", path = "android/app/src/main/AndroidManifest.xml" },
    },
  },
  {
    at = "Sat 02/07/2026 12:27",
    actor = "codex",
    summary = "Added a CLI script to create/update an owner admin user without hardcoding credentials in the repo.",
    changes = {
      { action = "add", path = "bin/create_admin_user.php" },
    },
  },
  {
    at = "Sat 02/07/2026 12:55",
    actor = "codex",
    summary = "Added a local .env to pin the runtime to XAMPP MySQL (ss_ltd) and avoid mismatched DB config between CLI and Apache.",
    changes = {
      { action = "add", path = ".env" },
    },
  },
  {
    at = "Sat 02/07/2026 12:56",
    actor = "codex",
    summary = "DB: enabled buffered MySQL queries and explicitly close cursors to prevent unbuffered-query errors during migrations and sequential DB operations.",
    changes = {
      { action = "update", path = "src/Database/Db.php" },
    },
  },
  {
    at = "Sat 02/07/2026 12:57",
    actor = "codex",
    summary = "Migrations (MySQL): execute statements via prepared statements and drain result sets to support migrations that use PREPARE/EXECUTE with SELECT fallbacks.",
    changes = {
      { action = "update", path = "bin/migrate.php" },
    },
  },
  {
    at = "Sat 02/07/2026 14:55",
    actor = "codex",
    summary = "WEB (dev/test): added a draggable always-on-top server log overlay for admins in debug mode (polls /app/dev/logs).",
    changes = {
      { action = "add", path = "src/Controllers/App/Dev/LogsController.php" },
      { action = "update", path = "src/routes.php" },
      { action = "update", path = "src/Views/layouts/app.php" },
      { action = "update", path = "src/Views/layouts/public.php" },
      { action = "update", path = "assets/js/app.js" },
      { action = "update", path = "assets/css/app.css" },
    },
  },
  {
    at = "Sat 02/07/2026 20:23",
    actor = "codex",
    summary = "WEB (dev/test): log basic HTTP activity to storage/logs/app.log in debug mode so the floating log overlay shows request flow (excludes /app/dev/logs).",
    changes = {
      { action = "update", path = "index.php" },
      { action = "update", path = "changelogs.lua" },
    },
  },
  {
    at = "Sat 02/07/2026 20:26",
    actor = "codex",
    summary = "WEB (dev/test): enable floating server log overlay for everyone in debug mode (including pre-login) and make /app/dev/logs public in debug but gated to private/LAN IPs.",
    changes = {
      { action = "update", path = "src/Views/layouts/app.php" },
      { action = "update", path = "src/Views/layouts/public.php" },
      { action = "update", path = "src/Views/layouts/auth.php" },
      { action = "update", path = "src/routes.php" },
      { action = "update", path = "src/Controllers/App/Dev/LogsController.php" },
      { action = "update", path = "changelogs.lua" },
    },
  },
  {
    at = "Sat 02/07/2026 20:29",
    actor = "codex",
    summary = "Docs: convert the Release Plan section in full_todos.md into a real checklist with explicit done/todo markers.",
    changes = {
      { action = "update", path = "full_todos.md" },
      { action = "update", path = "changelogs.lua" },
    },
  },
  {
    at = "Sat 02/07/2026 20:40",
    actor = "codex",
    summary = "QA: add a dev-only automated script to test upload/download boundaries near the 10MB limit (large file testing for release gate).",
    changes = {
      { action = "add", path = "bin/qa_large_files.php" },
      { action = "update", path = "docs/manual_test_checklist.md" },
      { action = "update", path = "changelogs.lua" },
    },
  },
  {
    at = "Sat 02/07/2026 20:44",
    actor = "codex",
    summary = "Docs: mark Release Plan step 19 as done after adding + running automated large file upload/download QA script.",
    changes = {
      { action = "update", path = "full_todos.md" },
      { action = "update", path = "changelogs.lua" },
    },
  },
  {
    at = "Sat 02/07/2026 20:52",
    actor = "codex",
    summary = "Tooling: allow selecting alternate env files via SS_ENV_FILE/--env, add staging env example, and harden .env file blocking.",
    changes = {
      { action = "update", path = "index.php" },
      { action = "update", path = "bin/migrate.php" },
      { action = "update", path = "bin/seed.php" },
      { action = "update", path = "bin/create_admin_user.php" },
      { action = "update", path = "bin/migrate_status.php" },
      { action = "update", path = "bin/health_db.php" },
      { action = "update", path = "bin/qa_large_files.php" },
      { action = "add", path = ".env.staging.example" },
      { action = "add", path = ".gitignore" },
      { action = "update", path = "docs/setup.md" },
      { action = "update", path = "changelogs.lua" },
    },
  },
  {
    at = "Sat 02/07/2026 21:12",
    actor = "codex",
    summary = "WEB (dev/test): add a Tools tab to the floating log overlay (quick login-as role switching, whoami, clear rate limits, quick links, quote-request autofill) via dev-only endpoints gated by APP_DEBUG + private IP.",
    changes = {
      { action = "add", path = "checklist_tests_todos.md" },
      { action = "add", path = "src/Controllers/App/Dev/ToolsController.php" },
      { action = "update", path = "src/routes.php" },
      { action = "update", path = "src/Views/layouts/app.php" },
      { action = "update", path = "src/Views/layouts/public.php" },
      { action = "update", path = "src/Views/layouts/auth.php" },
      { action = "update", path = "assets/js/app.js" },
      { action = "update", path = "assets/css/app.css" },
      { action = "update", path = "docs/setup.md" },
      { action = "update", path = "changelogs.lua" },
    },
  },
  {
    at = "Sat 02/07/2026 21:19",
    actor = "codex",
    summary = "WEB (dev/test): make dev tools + overlay base-path aware (subdirectory hosting) and add /login autofill helpers for seeded test accounts in debug mode.",
    changes = {
      { action = "update", path = "src/Views/layouts/app.php" },
      { action = "update", path = "src/Views/layouts/public.php" },
      { action = "update", path = "src/Views/layouts/auth.php" },
      { action = "update", path = "assets/js/app.js" },
      { action = "update", path = "checklist_tests_todos.md" },
      { action = "update", path = "changelogs.lua" },
    },
  },
  {
    at = "Sat 02/07/2026 21:27",
    actor = "codex",
    summary = "QA: add automated script to verify dev tools endpoints (whoami/users/login-as/logout/ratelimit clear) using CSRF extracted from /login.",
    changes = {
      { action = "add", path = "bin/qa_dev_tools.php" },
      { action = "update", path = "docs/manual_test_checklist.md" },
      { action = "update", path = "changelogs.lua" },
    },
  },
  {
    at = "Sat 02/07/2026 21:40",
    actor = "codex",
    summary = "Release: add local staging RC1 runner (separate DB + APP_DEBUG=0) and mark Release Plan steps 20-21 done for local staging flow.",
    changes = {
      { action = "add", path = "bin/rc1_local_staging.php" },
      { action = "update", path = "docs/manual_test_checklist.md" },
      { action = "update", path = "full_todos.md" },
      { action = "update", path = "changelogs.lua" },
    },
  },
  {
    at = "Sat 02/07/2026 21:53",
    actor = "codex",
    summary = "Release: fix staging RC1 runner reliability (create_admin_user --env arg parsing; avoid sparse env in proc_open; add cleanup cmd) and re-mark steps 20-21 as done after RC1 passes.",
    changes = {
      { action = "update", path = "bin/create_admin_user.php" },
      { action = "add", path = "bin/cleanup_dev_servers.cmd" },
      { action = "update", path = "bin/rc1_local_staging.php" },
      { action = "update", path = "full_todos.md" },
      { action = "update", path = "changelogs.lua" },
    },
  },
  {
    at = "Sat 02/08/2026 01:47",
    actor = "codex",
    summary = "Docs: freeze v0.1 scope and acceptance criteria (release gate step 1) - create scope freeze document and mark item complete.",
    changes = {
      { action = "add", path = "docs/v0.1_scope_freeze.md" },
      { action = "update", path = "full_todos.md" },
      { action = "update", path = "changelogs.lua" },
    },
  },
  {
    at = "Sat 02/08/2026 01:50",
    actor = "codex",
    summary = "Tooling: add QA and release helper scripts to assist with manual testing and release process (items 22-26).",
    changes = {
      { action = "add", path = "bin/qa_ops_checklist.php" },
      { action = "add", path = "bin/qa_prerelease.php" },
      { action = "add", path = "bin/release_helper.php" },
      { action = "update", path = "docs/manual_test_checklist.md" },
      { action = "update", path = "changelogs.lua" },
    },
  },
  {
    at = "Sat 02/08/2026 12:39",
    actor = "codex",
    summary = "Docs: comprehensive project analysis - errors list, improvements, and recommendations.",
    changes = {
      { action = "add", path = "docs/project_analysis.md" },
      { action = "update", path = "changelogs.lua" },
    },
  },
  {
    at = "Sat 02/08/2026 12:56",
    actor = "codex",
    summary = "Docs: create actionable todos_list2.md checklist from project analysis + add comprehensive README.md.",
    changes = {
      { action = "add", path = "todos_list2.md" },
      { action = "add", path = "README.md" },
      { action = "update", path = "changelogs.lua" },
    },
  },
  {
    at = "Sat 02/08/2026 13:24",
    actor = "codex",
    summary = "Core: implement centralized ErrorHandler with structured logging and log rotation.",
    changes = {
      { action = "add", path = "src/ErrorHandler.php" },
      { action = "add", path = "bin/rotate_logs.php" },
      { action = "update", path = "index.php" },
      { action = "update", path = "todos_list2.md" },
      { action = "update", path = "changelogs.lua" },
    },
  },
}
